# Generated by Django 3.1.3 on 2020-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancing',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
