# Generated by Django 3.1.3 on 2020-11-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yusers', '0002_dancing_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dancing',
            new_name='Actors',
        ),
    ]
