# Generated by Django 3.1.3 on 2020-11-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yusers', '0003_auto_20201113_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
