# Generated by Django 3.1.3 on 2020-11-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yusers', '0004_auto_20201113_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actors',
            old_name='id',
            new_name='actor_id',
        ),
    ]
