# Generated by Django 3.1.1 on 2020-10-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaasusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yaasuserlanguage',
            old_name='language',
            new_name='langguage',
        ),
    ]
