# Generated by Django 3.1.1 on 2020-10-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaasusers', '0002_auto_20201027_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yaasuserlanguage',
            old_name='langguage',
            new_name='language',
        ),
    ]
