# Generated by Django 3.1.1 on 2020-10-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaasusers', '0006_auto_20201029_1918'),
    ]

    operations = [
        
    ]
