# Generated by Django 3.1.1 on 2020-10-13 18:09

from django.db import migrations, models
import django.utils.timezone
import yaasusers.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('yaasusers', '0003_auto_20201006_1822'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='yaasuser',
            managers=[
                ('objects', yaasusers.manager.YaasUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='yaasuser',
            name='text',
        ),
        migrations.RemoveField(
            model_name='yaasuser',
            name='user',
        ),
        migrations.AddField(
            model_name='yaasuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yaasuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yaasuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='yaasuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='yaasuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='yaasuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yaasuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='yaasuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
