# Generated by Django 3.1.1 on 2020-10-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaasusers', '0005_yaasuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='YaasUserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=40, null=True)),
                ('lang_iso', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
            ],
        ),
        
    ]
