# Generated by Django 3.1.1 on 2020-10-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaasusers', '0007_remove_yaasuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='yaasuser',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yaasusers.yaasuserlanguage'),
        ),
    ]
