# Generated by Django 3.1.1 on 2020-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaasusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yaasuser',
            name='text',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
