# Generated by Django 3.1.1 on 2020-10-15 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0009_auto_20201015_1826'),
    ]

    pass

    # operations = [
    #     migrations.AlterField(
    #         model_name='auction',
    #         name='latest_bidder',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_bidder', to='yaasusers.yaasuser'),
    #     ),
    # ]
