# Generated by Django 3.1.1 on 2020-11-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201016_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
