# Generated by Django 3.1.1 on 2020-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201103_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='display_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='currency',
            field=models.CharField(choices=[('eur', 'EUR '), ('usd', 'USD'), ('gbp', 'GBP'), ('ngn', 'NGN')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
