# Generated by Django 3.1.1 on 2020-10-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
