# Generated by Django 3.1.1 on 2020-10-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201008_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
