# Generated by Django 3.1.1 on 2020-11-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='currency',
            field=models.CharField(choices=[('eur', 'EUR '), ('usd', 'USD'), ('gbp', 'GBP'), ('ngn', 'NGN')], default='EUR', max_length=3),
        ),
    ]
