# Generated by Django 3.1.1 on 2020-10-27 17:19

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('minimum_price', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('deadline', models.DateTimeField(default=auctions.models.get_deadline)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('latest_bid_date_time', models.DateTimeField(auto_now=True)),
                ('seller_total_bids', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('due', 'Due'), ('resolved', 'Resolved')], default='active', max_length=8)),
            ],
        ),
    ]
