# Generated by Django 3.1.1 on 2020-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currency',
            field=models.CharField(choices=[('eur', 'EUR '), ('usd', 'USD'), ('gbp', 'GBP'), ('ngn', 'NGN')], default='USD', max_length=3),
        ),
    ]
