# Generated by Django 3.1.1 on 2020-11-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_new_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='new_price',
            new_name='display_currency_value',
        ),
    ]
