# Generated by Django 3.1.1 on 2020-11-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201106_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='display_currency_value',
            new_name='display_price',
        ),
    ]
